name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.13.x
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.4.1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_SECRETS }}
    - name: Build image
      run: |
        ver=$(git describe --tags)
        docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{secrets.DOCKER_HUB_TOKEN}}
        docker build ./build -t surenpi/ks:${ver}
        docker push surenpi/ks:${ver}

        docker tag surenpi/ks:${ver} surenpi/ks:latest
        docker push surenpi/ks:latest
